Homepage
MattCo87/adndd pull request #2
Opened 2021-06-14 14:20 UTC by domGFX

Layout du site (page d'accueil) (responsive), templates à réutiliser sur les pages publiques.
Contient le header, le main, le footer et un menu de navigation.
Templates dans templates/

Architecture 7.1 SASS dans src/assets/scss
(compilateur / live watcher conseillé : Live Sass Compiler 5.0.3+)

2021-06-14 14:55 UTC, JulienIcar45 requested changes
un espace a droite du menu (vue ensemble et corrigé)

2021-06-14 15:23 UTC, JulienIcar45 approved these changes

2021-06-14 15:47 UTC, MattCo87 approved these changes

2021-06-14 16:00 UTC, TomLourdelle requested changes
affichage pied de page sur Ipad en vertical incorrecte (sort de la page)

2021-06-14 16:10 UTC, TomLourdelle approved these changes

2021-06-15 09:55 UTC, nicolasvauche approved these changes

2021-06-15 10:25 UTC, merged