Account
MattCo87/adndd pull request #20
Opened 2021-06-22 07:48 UTC by MattCo87

-Template des informations personnelles User
-Mise en place de la page de changement de mot de passe
-Modification du menu de navigation (ajout de lien)

2021-06-22 10:14 UTC, nicolasvauche requested changes
Conflit sur login.html.twig

2021-06-22 10:14 UTC, nicolasvauche commented on templates/security/login.html.twig
> +<<<<<<< HEAD
Ce conflit n'est pas résolu

2021-06-24 07:05 UTC, nicolasvauche requested changes
Password actual verif is not working

2021-06-24 08:05 UTC, TomLourdelle approved these changes

2021-06-24 08:05 UTC, domGFX approved these changes

2021-06-24 08:05 UTC, JulienIcar45 approved these changes

2021-06-24 09:53 UTC, nicolasvauche approved these changes

2021-06-24 09:57 UTC, merged